app/routes.php
<?php
//prueba
Route::get('/', function(){
	return View::make('hello');
});

Route::get('soporte', function(){
	return View::make('soporte');
});

Route::get('test', function(){
	return View::make('test');
});

Route::post('prueba', array(
	//'before' => 'csrf',
	'as' =>'prueba',
	'uses'=>'MyController@getIndex'
));

/*===========================================
=            Configuración Admin            =
===========================================*/

Config::set('syntara::views.dashboard-index', 'index');

View::composer('dashboard.layouts.dashboard.master', function ($view) {
	$view->with('siteName', 'Recargas Altcel');
	$view->nest('navPages', 'left-nav');
});


/*=====  End of Configuración Admin  ======*/

/*==================================================
=            Contadores Index Principal            =
==================================================*/

View::composer('index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

View::composer('sistema.altcel2.index', function($view) {
	$view->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first());
});

/*=====  End of Contadores Index Principal  ======*/

/*==================================================
=            Contadores Index Altcel            =
==================================================*/

View::composer('sistema.index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

/*=====  End of Contadores Index Altcel  ======*/

/*=================================
=            Catálogos            =
=================================*/

View::composer('sistema.cant_recargas.index', function($view){
	$view->with('cant_recargas', CantRecarga::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'catalogo'), function () {

	Route::resource('cant_recarga', 'CantRecargaController');

});

/*=====  End of Catálogos  ======*/


/*===============================
=            Sistema            =
===============================*/

View::composer('sistema.distribuidores.index', function ($view) {
  $view->with('distribuidores', Distribuidor::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions'), function () {

	Route::resource('distribuidor', 'DistribuidorController');
	Route::resource('recarga', 'RecargaController');
	Route::resource('ticket', 'TicketController');
	Route::resource('conecta', 'ConectaController');
	Route::resource('conecta_cliente', 'ConectaClienteController');
	Route::resource('altcel', 'AltcelController');
	Route::get(
		'ticket-update-altcel2',
		array(
			'as'   => 'ticket.update.altcel2',
			'uses' => 'TicketController@updateAltcel2')
	);
    Route::resource('venta_sim', 'VentaSimController');
    Route::post(
		'venta_sim/actualizar',
		array(
			'as'   => 'venta_sim.actualizar',
			'uses' => 'VentaSimController@actualizar')
	);
});



Route::group(array('before'=>'basicAuth|hasPermissions', 'prefix' => 'recurrente'), function() {
	
	Route::resource('recurrente', 'RecurrenteController');
	Route::resource('empresa', 'EmpresaController');
	Route::resource('telefono', 'TelefonoRecurrenteController');
	Route::resource('correo', 'CorreoRecurrenteController');

});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'altcel2'), function(){
	Route::resource('conecta','Altcel2Controller');

	Route::get(
		'monthly/{msisdn}',
		array(
			'as'   => 'altcel2.monthly',
			'uses' => 'Altcel2Controller@monthly')
	);

	Route::get(
		'save-monthly',
		array(
			'as'   => 'altcel2.save.monthly',
			'uses' => 'Altcel2Controller@saveMonthly')
	);

	Route::get(
		'get-offers-rates-diff/{msisdn}',
		array(
			'as'   => 'altcel2.get.offers.rates.diff',
			'uses' => 'Altcel2Controller@getOffersNRatesDiff')
	);

	Route::get(
		'change.product',
		array(
			'as'   => 'altcel2.change.product',
			'uses' => 'Altcel2Controller@changeProduct')
	);

	Route::get(
		'surplus/{msisdn}',
		array(
			'as'   => 'altcel2.surplus',
			'uses' => 'Altcel2Controller@surplus')
	);

	Route::get(
		'purchase-product',
		array(
			'as'   => 'altcel2.purchase',
			'uses' => 'Altcel2Controller@purchaseProduct')
	);

	Route::get(
		'verify-exists-msisdn',
		array(
			'as'   => 'altcel2.verify.exists.msisdn',
			'uses' => 'Altcel2Controller@verifyExistsMSISDN')
	);

	Route::get(
		'unbarring',
		array(
			'as'   => 'altcel2.unbarring',
			'uses' => 'Altcel2Controller@unbarring')
	);
});

/*=====  End of Sistema  ======*/

/*==================================
=  Recuperación de contraseña      =
==================================*/

Route::get(
	'recover_password/{id}/{resetCode}',
	array(
		'as'   => 'recover.newPassword',
		'uses' => 'RecoverController@newPassword')
);


Route::post(
	'recover_password/{id}/{resetCode}',
	array(
	'as'   => 'recover.newPasswordPost',
	'uses' => 'RecoverController@newPasswordPost')
);

Route::resource('recover', 'RecoverController');

/*=====  End of Recuperación de contraseña  ======*/

app/controllers/VentaSimController.php
<?php

class VentaSimController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout          = View::make('sistema.ventaSim.index');
		$this->layout->title   = 'Ventas SIM';
		// add breadcrumb to current page
		$this->layout->breadcrumb = array(
		  array(
		    'title' => 'Inicio',
		    'link'  => '/',
		    'icon'  => 'fas fa-home'
		  ),
		  array(
		    'title' => 'Ventas SIM',
		    'link'  => 'venta_sim',
		    'icon'  => 'fas fa-sim-card'
		  ),
		);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout          = View::make('sistema.ventaSim.portabilidad');
		$this->layout->title   = 'Ventas SIM Portabilidad';
		// add breadcrumb to current page
		$this->layout->breadcrumb = array(
		  array(
		    'title' => 'Inicio',
		    'link'  => '/',
		    'icon'  => 'fas fa-home'
		  ),
		  array(
		    'title' => 'Ventas SIM Portabilidad',
		    'link'  => 'venta_sim',
		    'icon'  => 'fas fa-sim-card'
		  ),
		);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $new = Input::all();
		$portabilidad = new Portabilidade();
        //return dump(Sentry::getUser());
		$distribuidor = "Distribuidor: ".Sentry::getUser()->first_name." ".Sentry::getUser()->last_name;
		Input::merge(['status'=>'Solicitud','promotor'=>$distribuidor]);
		$sim = Sim::where('iccid',Input::get('iccid'))->first();
		if ($sim == null) {
			return Redirect::back()->with('error','El numero de SIM NO existe, intenta de nuevo con otro SIM.')->withInput();
		}
		
		$sim = Sim::where('iccid',Input::get('iccid'))->where('usado',1)->count();
		if ($sim > 0) {
			return Redirect::back()->with('error','El numero de SIM ya ha sido utilizado, intenta de nuevo con otro SIM.')->withInput();
		}
		//return Input::all();
		
		//return ($sim);
		
		$portabilidad->create(Input::all());

		//return $portabilidad;

		$data = Input::all();
		/* Envio de Mail */
		Mail::send('emails.portabilidad', $data, function($message)
		{
	    $message->to('alejandro_rueda@altcel.com', 'Alejandro Rueda')->subject('Solicitud de Portabilidad');
	    $message->to('joel_maza@altcel.com', 'Joel Maza')->subject('Solicitud de Portabilidad');
	    $message->to('carlos_vazquez@altcel.com', 'Carlos Velazquez')->subject('Solicitud de Portabilidad');
	    $message->to('jonathan_gutierrez@altcel.com', 'Jonathan Gutierrez')->subject('Solicitud de Portabilidad');
	    $message->to('leopoldo_martinez@altcel.com', 'Leopoldo Martinez')->subject('Solicitud de Portabilidad');
	    $message->to('laura_coutino@altcel.com', 'Laura Coutiño Gonzalez')->subject('Solicitud de Portabilidad');
		});

		if (Mail::failures()) {
			return Redirect::back()->with('error','Ha ocurrido un error, intenta de nuevo más tarde!')->withInput();
		}else{
			$sim = Sim::where('iccid',Input::get('iccid'))->first();
			$sim->usado = 1;
			$sim->save();
			return Redirect::back()->with('success','Hemos recibido con éxito tus datos. Pronto nos pondrémos en contacto contigo!');
		}
		return dump(Input::all());
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout          = View::make('sistema.ventaSim.nueva');
		$this->layout->title   = 'Ventas SIM Linea Nueva';
		// add breadcrumb to current page
		$this->layout->breadcrumb = array(
		  array(
		    'title' => 'Inicio',
		    'link'  => '/',
		    'icon'  => 'fas fa-home'
		  ),
		  array(
		    'title' => 'Ventas SIM Linea Nueva',
		    'link'  => 'venta_sim',
		    'icon'  => 'fas fa-sim-card'
		  ),
		);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$url = "http://187.217.216.242/webhook/solicitudlineanueva";
        $client = new \GuzzleHttp\Client();

        $res = $client->request('POST', $url, [
        'debug' => FALSE,
        'form_params' => Input::all(),
        'headers' => [
            'Content-Type' => 'application/x-www-form-urlencoded',
        ]
        ]);
        $jsonString = $res->getBody();

        $respuesta = json_decode($jsonString, true);
        dump($respuesta);

	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

    public function actualizar()
	{
        $sim = Sim::where('iccid',Input::get('iccid'))->first();
		if ($sim == null) {
			return Redirect::back()->with('error','El numero de SIM NO existe, intenta de nuevo con otro SIM.')->withInput();
		}
		
		$sim = Sim::where('iccid',Input::get('iccid'))->where('usado',1)->count();
		if ($sim > 0) {
			return Redirect::back()->with('error','El numero de SIM ya ha sido utilizado, intenta de nuevo con otro SIM.')->withInput();
		}

        Input::merge(['solicito' => 'Distribuidor: '.Sentry::getUser()->first_name.' '.Sentry::getUser()->last_name, 'status' => 'Solicitud','price_plan_nuevo_id'=>8,'tarifa_nuevo_id'=>40]);
		$url = "http://187.217.216.242/webhook/solicitudlineanueva";
        $client = new \GuzzleHttp\Client();

        $res = $client->request('POST', $url, [
        'debug' => FALSE,
        'form_params' => Input::all(),
        'headers' => [
            'Content-Type' => 'application/x-www-form-urlencoded',
        ]
        ]);
        $jsonString = $res->getBody();

        $respuesta = json_decode($jsonString, true);
        
        $sim = Sim::where('iccid',Input::get('iccid'))->first();
        $sim->usado = 1;
        $sim->save();
        return Redirect::back()->with('success',$respuesta);

	}


}

app/views/sistema/ventaSim/index.blade.php
@extends('dashboard.layouts.dashboard.master')

{{ HTML::style('css/form.css') }}

{{ HTML::script('js/form.css') }}

@section('content')
@include('notifications')

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">SIM Portabilidad</div>
            <div class="panel-body text-center">
                <a href="{{ URL::route('venta_sim.create') }}">
                    <i class="fas fa-sim-card fa-3x"></i><br> Formulario Portabilidad
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">SIM Linea Nueva</div>
            <div class="panel-body text-center">
                <a href="{{ URL::route('venta_sim.edit') }}">
                    <i class="fas fa-sim-card fa-3x"></i><br> Formulario Linea Nueva
                </a>
            </div>
        </div>
    </div>
</div>

@stop

app/views/sistema/ventaSim/nueva.blade.php
@extends('dashboard.layouts.dashboard.master')

{{ HTML::style('css/form.css') }}

{{ HTML::script('js/form.css') }}

@section('content')
@include('notifications')
<h1>Portabilidad</h1>
<div class="container">

  @if (Session::has('error'))
  <div class="alert alert-danger alert-dismissable">
    <i class="fas fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <b><i class="fas fa-times"></i></b> {{ Session::get('error') }}
  </div>
  @endif

  @if (Session::has('success'))
    <div class="alert alert-success alert-dismissable">
      <i class="fas fa-check"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <b><i class="fas fa-thumbs-up"></i></b> {{ Session::get('success') }}
    </div>
  @endif
  
  {{ Form::open(['id'=>'form','method'=>'POST','route'=>'venta_sim.actualizar','role'=>'form','autocomplete'=>'off']) }}
<div class="row">
  <div class="col-md-3 mb-3">
      <label for="validationServer013">Nombre y Apellidos</label>
      <input type="text" value="{{ Input::old('nombre') }}" class="form-control" id="validationServer013" placeholder="Nombre y Apellidos" name="nombre" required>
  </div>

  <div class="col-md-3 mb-3">
      <label for="validationServer013">CURP</label>
      <input type="text" value="{{ Input::old('curp') }}" class="form-control" id="validationServer013" placeholder="CURP" name="curp" required>
  </div>

  {{-- <div class="col-md-3 mb-3">
      <label for="validationServer013">Número Telefonico</label>
      <input type="text" value="{{ Input::old('numero') }}" class="form-control" id="validationServer013" placeholder="Número Telefonico" name="numero" required>
  </div>

  <div class="col-md-3 mb-3">
      <label for="validationServer013">NIP</label>
      <input type="text" value="{{ Input::old('nip') }}" class="form-control" id="validationServer013" placeholder="NIP" name="nip" required>
  </div> --}}
  
</div>
<div class="row">
  {{-- <div class="col-md-3 mb-3">
      <label for="validationServer013">Fecha de Portabilidad</label>
      <input type="date" value="{{ Input::old('fecha') }}" class="form-control" id="validationServer013" placeholder="Fecha de Portabilidad" name="fecha" required>
  </div> --}}

  <div class="col-md-3 mb-3">
      <label for="validationServer013">SIM</label>
      <input type="text" value="{{ Input::old('iccid') }}" class="form-control" id="validationServer013" placeholder="SIM" name="iccid" required>
  </div>

  <div class="col-md-3 mb-3">
      <label for="validationServer013">INE</label>
      <input type="text" value="{{ Input::old('ine') }}" class="form-control" id="validationServer013" placeholder="INE" name="ine" required>
  </div>

  <div class="col-md-3 mb-3">
      <label for="validationServer013">Dirección</label>
      <input type="text" value="{{ Input::old('direccion') }}" class="form-control" id="validationServer013" placeholder="Dirección" name="direccion" required>
  </div>
</div>
<div class="row">
  {{-- <div class="col-md-3 mb-3">
      <label for="validationServer013">Compañia</label>
      <!--<input type="text" value="{{ Input::old('') }}" class="form-control" id="validationServer013" placeholder="Compañia" name="cia" required>-->
      <select class="form-control" id="inputGroupSelect01" name="cia" required>
          <option {{ (Input::old("cia") == 'Compañía Anterior' ? "selected":"") }} value="0"> Compañía Anterior</option>
          <option {{ (Input::old("cia") == 'ALO' ? "selected":"") }} value="ALO">ALO</option>
          <option {{ (Input::old("cia") == 'AT&T' ? "selected":"") }} value="AT&T">AT&T</option>
          <option {{ (Input::old("cia") == 'BUENOCELL' ? "selected":"") }} value="BUENOCELL">BUENOCELL</option>
          <option {{ (Input::old("cia") == 'CIERTO' ? "selected":"") }} value="CIERTO">CIERTO</option>
          <option {{ (Input::old("cia") == 'FLASH MOBILE' ? "selected":"") }} value="FLASH MOBILE">FLASH MOBILE</option>
          <option {{ (Input::old("cia") == 'FREEDOMPOP' ? "selected":"") }} value="FREEDOMPOP">FREEDOMPOP</option>
          <option {{ (Input::old("cia") == 'HER MOBILE' ? "selected":"") }} value="HER MOBILE">HER MOBILE</option>
          <option {{ (Input::old("cia") == 'MAZ TIEMPO' ? "selected":"") }} value="MAZ TIEMPO">MAZ TIEMPO</option>
          <option {{ (Input::old("cia") == 'MOVISTAR' ? "selected":"") }} value="MOVISTAR">MOVISTAR</option>
          <option {{ (Input::old("cia") == 'OUI' ? "selected":"") }} value="OUI">OUI</option>
          <option {{ (Input::old("cia") == 'QBOCEL' ? "selected":"") }} value="QBOCEL">QBOCEL</option>
          <option {{ (Input::old("cia") == 'SIMPATI' ? "selected":"") }} value="SIMPATI">SIMPATI</option>
          <option {{ (Input::old("cia") == 'SIMPLII' ? "selected":"") }} value="SIMPLII">SIMPLII</option>
          <option {{ (Input::old("cia") == 'SORIANA' ? "selected":"") }} value="SORIANA">SORIANA</option>
          <option {{ (Input::old("cia") == 'TELCEL' ? "selected":"") }} value="TELCEL">TELCEL</option>
          <option {{ (Input::old("cia") == 'TOKAMÓVIL' ? "selected":"") }} value="TOKAMÓVIL">TOKAMÓVIL</option>
          <option {{ (Input::old("cia") == 'UNEFON' ? "selected":"") }} value="UNEFON">UNEFON</option>
          <option {{ (Input::old("cia") == 'VIRGIN MOBILE' ? "selected":"") }} value="VIRGIN MOBILE">VIRGIN MOBILE</option>
          <option {{ (Input::old("cia") == 'WEEX' ? "selected":"") }} value="WEEX">WEEX</option>
      </select>
  </div> --}}
  <div class="col-md-3 mb-3">
      {{-- <label for="validationServer013">Promoción</label>
      <select id="promo" name="promo" class="form-control" required>
          <option {{ (Input::old("promo") == 'Seleccione Promo' ? "selected":"") }} value="0"> Seleccione Promo</option>
          <option {{ (Input::old("promo")=='Altcel 40 - Escala Recarga'?"selected":"") }} value="Altcel 40 - Escala Recarga">Altcel 40 - Escala Recarga</option>
          <option {{ (Input::old("promo") == 'Altcel Ilimitado' ? "selected":"") }} value="Altcel Ilimitado">Altcel Ilimitado</option>
          <option {{ (Input::old("promo") == 'Altcel 80 Saldo Regalo 3 meses' ? "selected":"") }} value="Altcel 80 Saldo Regalo 3 meses">Altcel 80 Saldo Regalo 3 meses</option>
      </select> --}}
  </div>
</div>
<br>
<div class="row">
  <button class="btn btn-primary" type="submit">Guardar</button>
</div>
</form></div>
@endsection

app/views/sistema/ventaSim/portabilidad.blade.php
@extends('dashboard.layouts.dashboard.master')

{{ HTML::style('css/form.css') }}

{{ HTML::script('js/form.css') }}

@section('content')
@include('notifications')

<h1>Portabilidad</h1>
      <div class="container">

        @if (Session::has('error'))
        <div class="alert alert-danger alert-dismissable">
          <i class="fas fa-ban"></i>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <b><i class="fas fa-times"></i></b> {{ Session::get('error') }}
        </div>
        @endif

        @if (Session::has('success'))
          <div class="alert alert-success alert-dismissable">
            <i class="fas fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <b><i class="fas fa-thumbs-up"></i></b> {{ Session::get('success') }}
          </div>
        @endif
		
        {{ Form::open(['id'=>'form','method'=>'POST','route'=>'venta_sim.store','role'=>'form','autocomplete'=>'off']) }}
    <div class="row">
        <div class="col-md-3 mb-3">
            <label for="validationServer013">Nombre y Apellidos</label>
            <input type="text" value="{{ Input::old('nombre') }}" class="form-control" id="validationServer013" placeholder="Nombre y Apellidos" name="nombre" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">CURP</label>
            <input type="text" value="{{ Input::old('curp') }}" class="form-control" id="validationServer013" placeholder="CURP" name="curp" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">Número Telefonico</label>
            <input type="text" value="{{ Input::old('numero') }}" class="form-control" id="validationServer013" placeholder="Número Telefonico" name="numero" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">NIP</label>
            <input type="text" value="{{ Input::old('nip') }}" class="form-control" id="validationServer013" placeholder="NIP" name="nip" required>
        </div>
        
    </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <label for="validationServer013">Fecha de Portabilidad</label>
            <input type="date" value="{{ Input::old('fecha') }}" class="form-control" id="validationServer013" placeholder="Fecha de Portabilidad" name="fecha" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">SIM</label>
            <input type="text" value="{{ Input::old('iccid') }}" class="form-control" id="validationServer013" placeholder="SIM" name="iccid" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">INE</label>
            <input type="text" value="{{ Input::old('ine') }}" class="form-control" id="validationServer013" placeholder="INE" name="ine" required>
        </div>

        <div class="col-md-3 mb-3">
            <label for="validationServer013">Dirección</label>
            <input type="text" value="{{ Input::old('direccion') }}" class="form-control" id="validationServer013" placeholder="Dirección" name="direccion" required>
        </div>
    </div>
	<div class="row">
        <div class="col-md-3 mb-3">
            <label for="validationServer013">Compañia</label>
            <!--<input type="text" value="{{ Input::old('') }}" class="form-control" id="validationServer013" placeholder="Compañia" name="cia" required>-->
            <select class="form-control" id="inputGroupSelect01" name="cia" required>
                <option {{ (Input::old("cia") == 'Compañía Anterior' ? "selected":"") }} value="0"> Compañía Anterior</option>
                <option {{ (Input::old("cia") == 'ALO' ? "selected":"") }} value="ALO">ALO</option>
                <option {{ (Input::old("cia") == 'AT&T' ? "selected":"") }} value="AT&T">AT&T</option>
                <option {{ (Input::old("cia") == 'BUENOCELL' ? "selected":"") }} value="BUENOCELL">BUENOCELL</option>
                <option {{ (Input::old("cia") == 'CIERTO' ? "selected":"") }} value="CIERTO">CIERTO</option>
                <option {{ (Input::old("cia") == 'FLASH MOBILE' ? "selected":"") }} value="FLASH MOBILE">FLASH MOBILE</option>
                <option {{ (Input::old("cia") == 'FREEDOMPOP' ? "selected":"") }} value="FREEDOMPOP">FREEDOMPOP</option>
                <option {{ (Input::old("cia") == 'HER MOBILE' ? "selected":"") }} value="HER MOBILE">HER MOBILE</option>
                <option {{ (Input::old("cia") == 'MAZ TIEMPO' ? "selected":"") }} value="MAZ TIEMPO">MAZ TIEMPO</option>
                <option {{ (Input::old("cia") == 'MOVISTAR' ? "selected":"") }} value="MOVISTAR">MOVISTAR</option>
                <option {{ (Input::old("cia") == 'OUI' ? "selected":"") }} value="OUI">OUI</option>
                <option {{ (Input::old("cia") == 'QBOCEL' ? "selected":"") }} value="QBOCEL">QBOCEL</option>
                <option {{ (Input::old("cia") == 'SIMPATI' ? "selected":"") }} value="SIMPATI">SIMPATI</option>
                <option {{ (Input::old("cia") == 'SIMPLII' ? "selected":"") }} value="SIMPLII">SIMPLII</option>
                <option {{ (Input::old("cia") == 'SORIANA' ? "selected":"") }} value="SORIANA">SORIANA</option>
                <option {{ (Input::old("cia") == 'TELCEL' ? "selected":"") }} value="TELCEL">TELCEL</option>
                <option {{ (Input::old("cia") == 'TOKAMÓVIL' ? "selected":"") }} value="TOKAMÓVIL">TOKAMÓVIL</option>
                <option {{ (Input::old("cia") == 'UNEFON' ? "selected":"") }} value="UNEFON">UNEFON</option>
                <option {{ (Input::old("cia") == 'VIRGIN MOBILE' ? "selected":"") }} value="VIRGIN MOBILE">VIRGIN MOBILE</option>
                <option {{ (Input::old("cia") == 'WEEX' ? "selected":"") }} value="WEEX">WEEX</option>
            </select>
        </div>
		<div class="col-md-3 mb-3">
            <label for="validationServer013">Promoción</label>
            <select id="promo" name="promo" class="form-control" required>
                <option {{ (Input::old("promo") == 'Seleccione Promo' ? "selected":"") }} value="0"> Seleccione Promo</option>
                <option {{ (Input::old("promo")=='Altcel 40 - Escala Recarga'?"selected":"") }} value="Altcel 40 - Escala Recarga">Altcel 40 - Escala Recarga</option>
                <option {{ (Input::old("promo") == 'Altcel Ilimitado' ? "selected":"") }} value="Altcel Ilimitado">Altcel Ilimitado</option>
                <option {{ (Input::old("promo") == 'Altcel 80 Saldo Regalo 3 meses' ? "selected":"") }} value="Altcel 80 Saldo Regalo 3 meses">Altcel 80 Saldo Regalo 3 meses</option>
            </select>
        </div>
	</div>
    <br>
    <div class="row">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
</form></div>

@endsection