app/routes.php
<?php
//prueba
Route::get('/', function(){
	return View::make('hello');
});

Route::get('soporte', function(){
	return View::make('soporte');
});

Route::get('test', function(){
	return View::make('test');
});

Route::post('prueba', array(
	//'before' => 'csrf',
	'as' =>'prueba',
	'uses'=>'MyController@getIndex'
));

/*===========================================
=            Configuración Admin            =
===========================================*/

Config::set('syntara::views.dashboard-index', 'index');

View::composer('dashboard.layouts.dashboard.master', function ($view) {
	$view->with('siteName', 'Recargas Altcel');
	$view->nest('navPages', 'left-nav');
});


/*=====  End of Configuración Admin  ======*/

/*==================================================
=            Contadores Index Principal            =
==================================================*/

View::composer('index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

View::composer('sistema.altcel2.index', function($view) {
	$view->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first());
});

/*=====  End of Contadores Index Principal  ======*/

/*==================================================
=            Contadores Index Altcel            =
==================================================*/

View::composer('sistema.index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

/*=====  End of Contadores Index Altcel  ======*/

/*=================================
=            Catálogos            =
=================================*/

View::composer('sistema.cant_recargas.index', function($view){
	$view->with('cant_recargas', CantRecarga::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'catalogo'), function () {

	Route::resource('cant_recarga', 'CantRecargaController');

});

/*=====  End of Catálogos  ======*/


/*===============================
=            Sistema            =
===============================*/

View::composer('sistema.distribuidores.index', function ($view) {
  $view->with('distribuidores', Distribuidor::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions'), function () {

	Route::resource('distribuidor', 'DistribuidorController');
	Route::resource('recarga', 'RecargaController');
	Route::resource('ticket', 'TicketController');
	Route::resource('conecta', 'ConectaController');
	Route::resource('conecta_cliente', 'ConectaClienteController');
	Route::resource('altcel', 'AltcelController');
	Route::get(
		'ticket-update-altcel2',
		array(
			'as'   => 'ticket.update.altcel2',
			'uses' => 'TicketController@updateAltcel2')
	);
    Route::resource('venta_sim', 'VentaSimController');
    Route::post(
		'venta_sim/actualizar',
		array(
			'as'   => 'venta_sim.actualizar',
			'uses' => 'VentaSimController@actualizar')
	);
});



Route::group(array('before'=>'basicAuth|hasPermissions', 'prefix' => 'recurrente'), function() {
	
	Route::resource('recurrente', 'RecurrenteController');
	Route::resource('empresa', 'EmpresaController');
	Route::resource('telefono', 'TelefonoRecurrenteController');
	Route::resource('correo', 'CorreoRecurrenteController');

});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'altcel2'), function(){
	Route::resource('conecta','Altcel2Controller');

	Route::get(
		'monthly/{msisdn}',
		array(
			'as'   => 'altcel2.monthly',
			'uses' => 'Altcel2Controller@monthly')
	);

	Route::get(
		'save-monthly',
		array(
			'as'   => 'altcel2.save.monthly',
			'uses' => 'Altcel2Controller@saveMonthly')
	);

	Route::get(
		'get-offers-rates-diff/{msisdn}',
		array(
			'as'   => 'altcel2.get.offers.rates.diff',
			'uses' => 'Altcel2Controller@getOffersNRatesDiff')
	);

	Route::get(
		'change.product',
		array(
			'as'   => 'altcel2.change.product',
			'uses' => 'Altcel2Controller@changeProduct')
	);

	Route::get(
		'surplus/{msisdn}',
		array(
			'as'   => 'altcel2.surplus',
			'uses' => 'Altcel2Controller@surplus')
	);

	Route::get(
		'purchase-product',
		array(
			'as'   => 'altcel2.purchase',
			'uses' => 'Altcel2Controller@purchaseProduct')
	);

	Route::get(
		'verify-exists-msisdn',
		array(
			'as'   => 'altcel2.verify.exists.msisdn',
			'uses' => 'Altcel2Controller@verifyExistsMSISDN')
	);

	Route::get(
		'unbarring',
		array(
			'as'   => 'altcel2.unbarring',
			'uses' => 'Altcel2Controller@unbarring')
	);
});

/*=====  End of Sistema  ======*/

/*==================================
=  Recuperación de contraseña      =
==================================*/

Route::get(
	'recover_password/{id}/{resetCode}',
	array(
		'as'   => 'recover.newPassword',
		'uses' => 'RecoverController@newPassword')
);


Route::post(
	'recover_password/{id}/{resetCode}',
	array(
	'as'   => 'recover.newPasswordPost',
	'uses' => 'RecoverController@newPasswordPost')
);

Route::resource('recover', 'RecoverController');

/*=====  End of Recuperación de contraseña  ======*/

app/views/dashboard/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ trans('syntara::all.signin') }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ asset('favicon.ico') }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../login/css/util.css">
	<link rel="stylesheet" type="text/css" href="../login/css/main.css">
<!--===============================================================================================-->

</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<h1 class="login100-form-btn fs-50">
					RECARGAS
				</h1>
			</div>
			<div class="wrap-login100">
				<form id="login-form" class="login100-form validate-form" method="post">
					<span class="login100-form-title p-b-34">
						{{ trans('syntara::all.signin') }}
					</span>

					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20 form-group" data-validate="Escribe tu nombre de usuario">
						@if($loginAttribute === 'email')

							<input id="first-name" type="text" class="form-control input100" placeholder="{{ trans('syntara::all.email') }}" name="email" id="email">

						@elseif($loginAttribute === 'username')

							<input id="first-name" type="text" class="form-control input100" placeholder="{{ trans('syntara::users.username') }}" name="username" id="username">

						@endif

						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20 form-group" data-validate="Escribe tu contraseña">
						<input class="input100" type="password" name="pass" placeholder="{{ trans('syntara::all.password') }}">
						<span class="focus-input100"></span>
					</div>
					<br>
					<div class="footer" id="main-container" style="text-align: center;"></div>
					<br>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn btn" data-loading-text="Ingresando...">
							Login
						</button>
					</div>


					<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Olvidaste tu
						</span>

						<a href="{{ URL::route('recover.index') }}" class="txt2">
							contraseña?
						</a>
					</div>

				</form>

				<div class="login100-more" style="background-image: url('../images/portada.png');"></div>
			</div>
		</div>
	</div>



	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="../login/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../login/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../login/vendor/bootstrap/js/popper.js"></script>
	<script src="../login/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../login/vendor/select2/select2.min.js"></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
	<script src="../login/vendor/daterangepicker/moment.min.js"></script>
	<script src="../login/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../login/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../login/js/main.js"></script>

	<!-- jQuery 2.0.2 -->
	<script src="{{ asset('js/jquery.min.js') }}"></script>
	<script src="{{ asset('packages/mrjuliuss/syntara/assets/js/dashboard/base.js') }}"></script>

	<script type="text/javascript" src="{{ asset('packages/mrjuliuss/syntara/assets/js/dashboard/login.js') }}"></script>

</body>
</html>

app/views/dashboard/new-password.blade.php
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


{{ HTML::script('js/new-pass.js') }}

<div class="row">
  @include('notifications')
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-12">
		<h1>Cambio de contraseña</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<p class="text-center">Utilice el siguiente formulario para cambiar su contraseña.</p>
			{{ Form::open(['id'=>'passwordForm']) }}
				<input type="password" class="input-lg form-control" name="password" id="password" placeholder="Nueva Contraseña" autocomplete="off">
				<div class="row">
					<div class="col-sm-6">
						<span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 8 caracteres de largo<br>
						<span id="ucase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 letra mayúscula
					</div>
					<div class="col-sm-6">
						<span id="lcase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 letra minuscula<br>
						<span id="num" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 número
					</div>
				</div>
				<input type="password" class="input-lg form-control" name="password_confirmation" id="password_confirmation" placeholder="Repetir Contraseña" autocomplete="off">
				<div class="row">
					<div class="col-sm-12">
						<span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Contraseñas coinciden
					</div>
				</div>
				<input type="submit" class="col-xs-12 btn btn-primary btn-load btn-lg" data-loading-text="Cambiando la Contraseña..." value="Cambiar contraseña">
			{{ Form::close() }}
		</div><!--/col-sm-6-->
	</div><!--/row-->
</div>

app/views/dashboard/recover.blade.php
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

{{ HTML::style(asset('css/app.css')) }}

<br><br>
<div class="form-gap"></div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="text-center">
                  <h3><i class="fas fa-user-lock fa-5x"></i></h3>
                  <h2 class="text-center">¿Olvidaste tu contraseña?</h2>
                  <p>Puedes restablecer tu contraseña aquí.</p>
                  <div class="panel-body">
    
                    {{ Form::open(['id'=>'register-form', 'role'=>'form', 'autocomplete'=>'off', 'class'=>'form']) }}
    
                      <div class="form-group">
                        <div class="input-group">
                          <span class="input-group-addon"><i class="glyphicon glyphicon-user color-blue"></i></span>
                          <input id="email" name="email" placeholder="Usuario" class="form-control"  type="text">
                        </div>
                      </div>
                      <div class="form-group">
                        <input name="recover-submit" class="btn btn-lg btn-primary btn-block" value="Restablecer Contraseña" type="submit">
                      </div>
                    {{ Form::close() }}      
                  </div>
                </div>
              </div>
            </div>
          </div>
	</div>
</div>