app/routes.php
<?php
//prueba
Route::get('/', function(){
	return View::make('hello');
});

Route::get('soporte', function(){
	return View::make('soporte');
});

Route::get('test', function(){
	return View::make('test');
});

Route::post('prueba', array(
	//'before' => 'csrf',
	'as' =>'prueba',
	'uses'=>'MyController@getIndex'
));

/*===========================================
=            Configuración Admin            =
===========================================*/

Config::set('syntara::views.dashboard-index', 'index');

View::composer('dashboard.layouts.dashboard.master', function ($view) {
	$view->with('siteName', 'Recargas Altcel');
	$view->nest('navPages', 'left-nav');
});


/*=====  End of Configuración Admin  ======*/

/*==================================================
=            Contadores Index Principal            =
==================================================*/

View::composer('index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

View::composer('sistema.altcel2.index', function($view) {
	$view->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first());
});

/*=====  End of Contadores Index Principal  ======*/

/*==================================================
=            Contadores Index Altcel            =
==================================================*/

View::composer('sistema.index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

/*=====  End of Contadores Index Altcel  ======*/

/*=================================
=            Catálogos            =
=================================*/

View::composer('sistema.cant_recargas.index', function($view){
	$view->with('cant_recargas', CantRecarga::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'catalogo'), function () {

	Route::resource('cant_recarga', 'CantRecargaController');

});

/*=====  End of Catálogos  ======*/


/*===============================
=            Sistema            =
===============================*/

View::composer('sistema.distribuidores.index', function ($view) {
  $view->with('distribuidores', Distribuidor::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions'), function () {

	Route::resource('distribuidor', 'DistribuidorController');
	Route::resource('recarga', 'RecargaController');
	Route::resource('ticket', 'TicketController');
	Route::resource('conecta', 'ConectaController');
	Route::resource('conecta_cliente', 'ConectaClienteController');
	Route::resource('altcel', 'AltcelController');
	Route::get(
		'ticket-update-altcel2',
		array(
			'as'   => 'ticket.update.altcel2',
			'uses' => 'TicketController@updateAltcel2')
	);
    Route::resource('venta_sim', 'VentaSimController');
    Route::post(
		'venta_sim/actualizar',
		array(
			'as'   => 'venta_sim.actualizar',
			'uses' => 'VentaSimController@actualizar')
	);
});



Route::group(array('before'=>'basicAuth|hasPermissions', 'prefix' => 'recurrente'), function() {
	
	Route::resource('recurrente', 'RecurrenteController');
	Route::resource('empresa', 'EmpresaController');
	Route::resource('telefono', 'TelefonoRecurrenteController');
	Route::resource('correo', 'CorreoRecurrenteController');

});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'altcel2'), function(){
	Route::resource('conecta','Altcel2Controller');

	Route::get(
		'monthly/{msisdn}',
		array(
			'as'   => 'altcel2.monthly',
			'uses' => 'Altcel2Controller@monthly')
	);

	Route::get(
		'save-monthly',
		array(
			'as'   => 'altcel2.save.monthly',
			'uses' => 'Altcel2Controller@saveMonthly')
	);

	Route::get(
		'get-offers-rates-diff/{msisdn}',
		array(
			'as'   => 'altcel2.get.offers.rates.diff',
			'uses' => 'Altcel2Controller@getOffersNRatesDiff')
	);

	Route::get(
		'change.product',
		array(
			'as'   => 'altcel2.change.product',
			'uses' => 'Altcel2Controller@changeProduct')
	);

	Route::get(
		'surplus/{msisdn}',
		array(
			'as'   => 'altcel2.surplus',
			'uses' => 'Altcel2Controller@surplus')
	);

	Route::get(
		'purchase-product',
		array(
			'as'   => 'altcel2.purchase',
			'uses' => 'Altcel2Controller@purchaseProduct')
	);

	Route::get(
		'verify-exists-msisdn',
		array(
			'as'   => 'altcel2.verify.exists.msisdn',
			'uses' => 'Altcel2Controller@verifyExistsMSISDN')
	);

	Route::get(
		'unbarring',
		array(
			'as'   => 'altcel2.unbarring',
			'uses' => 'Altcel2Controller@unbarring')
	);
});

/*=====  End of Sistema  ======*/

/*==================================
=  Recuperación de contraseña      =
==================================*/

Route::get(
	'recover_password/{id}/{resetCode}',
	array(
		'as'   => 'recover.newPassword',
		'uses' => 'RecoverController@newPassword')
);


Route::post(
	'recover_password/{id}/{resetCode}',
	array(
	'as'   => 'recover.newPasswordPost',
	'uses' => 'RecoverController@newPasswordPost')
);

Route::resource('recover', 'RecoverController');

/*=====  End of Recuperación de contraseña  ======*/

app/views/sistema/distribuidores/create.blade.php
@extends('dashboard.layouts.dashboard.master')


{{ HTML::style('css/form.css') }}

{{ HTML::script('js/form.css') }}

@section('content')
@include('notifications')
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-danger">
				<div class="panel-body">
					<h3>
            <?php $icon = end($breadcrumb)['icon']; ?>
            <i class="<?php echo (strpos($icon,'fa-')!==false)?'fa':'glyphicon '; ?> {{$icon}}"></i>
            {{end($breadcrumb)['title']}}
					</h3>
					<hr>
					<?php
						if (isset($distribuidor)) {
							$method = 'PUT';
							$route = ['distribuidor.update',$distribuidor->id];
						} else {
							$method = 'POST';
							$route = 'distribuidor.store';
						}
					?>
					{{ Form::open(['id'=>'form','method'=>$method,'route'=>$route,'role'=>'form']) }}

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Nombre</label>
			              {{ Form::text('first_name', Input::old('first_name', isset($distribuidor)?$distribuidor->user->first_name:null), ['class'=>'form-control', 'required', 'placeholder'=>'Nombre']) }}
			            </div>					
								</div>

								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Apellido</label>
			              {{ Form::text('last_name', Input::old('last_name', isset($distribuidor)?$distribuidor->user->last_name:null), ['class'=>'form-control', 'required', 'placeholder'=>'Apellido']) }}
			            </div>					
								</div>

								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Distribuidor</label>
			              {{ Form::text('distribuidor', Input::old('distribuidor', isset($distribuidor)?$distribuidor->distribuidor:null), ['class'=>'form-control', 'required', 'placeholder'=>'Distribuidor']) }}
			            </div>					
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Teléfono</label>
			              {{ Form::text('telefono', Input::old('telefono', isset($distribuidor)?$distribuidor->telefono:null), ['class'=>'form-control', 'required', 'placeholder'=>'Teléfono']) }}
			            </div>					
								</div>

								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Usuario</label>
			              {{ Form::text('username', Input::old('username', isset($distribuidor)?$distribuidor->user->username:null), ['class'=>'form-control', 'required', 'placeholder'=>'Usuario',isset($distribuidor)?'Readonly':'']) }}
			            </div>					
								</div>

								<div class="col-md-4">
									<div class="form-group float-label-control">
			              <label for="">Correo Electrónico</label>
			              {{ Form::email('email', Input::old('email', isset($distribuidor)?$distribuidor->user->email:null), ['class'=>'form-control', 'required', 'placeholder'=>'Correo Electrónico',isset($distribuidor)?'Readonly':'']) }}
			            </div>					
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-3">
									<div class="form-group float-label-control">
			              <label for="">ID de Grupo</label>
			              {{ Form::text('id_grp', Input::old('id_grp', isset($distribuidor)?$distribuidor->id_grp:null), ['class'=>'form-control', 'required', 'placeholder'=>'ID de Grupo']) }}
			            </div>					
								</div>

								<div class="col-md-3">
									<div class="form-group float-label-control">
			              <label for="">ID de Cadena</label>
			              {{ Form::text('id_chain', Input::old('id_chain', isset($distribuidor)?$distribuidor->id_chain:null), ['class'=>'form-control', 'required', 'placeholder'=>'ID de Cadena']) }}
			            </div>					
								</div>

								<div class="col-md-3">
									<div class="form-group float-label-control">
			              <label for="">ID de Tienda</label>
			              {{ Form::text('id_merchant', Input::old('id_merchant', isset($distribuidor)?$distribuidor->id_merchant:null), ['class'=>'form-control', 'required', 'placeholder'=>'ID de Tienda']) }}
			            </div>					
								</div>

								<div class="col-md-3">
									<div class="form-group float-label-control">
			              <label for="">ID de POS</label>
			              {{ Form::text('id_pos', Input::old('id_pos', isset($distribuidor)?$distribuidor->id_pos:null), ['class'=>'form-control', 'required', 'placeholder'=>'ID de POS']) }}
			            </div>					
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-12">
									<div class="form-group float-label-control">
			              <label for="">URL de Tienda</label>
			              {{ Form::text('url', Input::old('url', isset($distribuidor)?$distribuidor->url:null), ['class'=>'form-control', 'required', 'placeholder'=>'URL de Tienda']) }}
			            </div>					
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-12">
									<div class="form-group float-label-control">
			              <label for="">Observaciones</label>
			              {{ Form::text('observaciones', Input::old('observaciones', isset($distribuidor)?$distribuidor->observaciones:null), ['class'=>'form-control', 'placeholder'=>'Observaciones']) }}
			            </div>					
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								<div class="col-md-6">
									{{ Form::submit('Guardar', array('class'=>'btn btn-primary')) }}
								</div>
							</div>
						</div>
	
					{{ Form::close() }}
				</div>
			</div>
		</div>
	</div>
@stop

@section('scripts')
	<script type="text/javascript">
  	
  	$("#form").validate();

  </script>
@endsection

app/views/sistema/distribuidores/index.blade.php
@extends('dashboard.layouts.dashboard.master')

@section('content')

@include('notifications')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-danger">
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">
							<a href="{{ URL::route('distribuidor.create') }}"><i class="fas fa-plus"></i> Agregar Distribuidor</a>
						</div>
					</div>
					<br>
					<table class="table" id="distribuidores">
					  <thead>
					  	<tr>
					  		<th>Nombre</th>
					  		<th>Distribuidor</th>
					  		<th>Correo</th>
					  		<th>Teléfono</th>
					  		<th>Acciones</th>
					  	</tr>
					  </thead>
					  <tbody>
					  	@foreach ($distribuidores as $distribuidor)
						  	<tr class="text-center">
						  		<td>{{ $distribuidor->user->last_name }} {{ $distribuidor->user->first_name }}</td>
						  		<td>{{ $distribuidor->distribuidor }}</td>
						  		<td>{{ $distribuidor->user->email }}</td>
						  		<td>{{ $distribuidor->telefono }}</td>
						  		<td>
								  	<div class="btn-group" role="group" aria-label="acciones">
								  		<a href="{{ URL::route('distribuidor.show', $distribuidor->id) }}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i> Info</a>
										<a class="btn btn-sm btn-info" href="{{ URL::route('distribuidor.edit', $distribuidor->id) }}" data-toggle="tooltip" data-placement="top" title="Editar Distribuidor"><i class="fas fa-pencil-alt"></i> Editar</a>
										<a class="btn btn-sm btn-danger" href="#" data-placement="top" title="Borrar Distribuidor" data-toggle="modal" data-target=".bs-example-modal-lg{{ $distribuidor->id }}"><i class="fas fa-trash"></i> Borrar</a>
						  		</td>
						  	</tr>
						  		<div class="modal fade bs-example-modal-lg{{ $distribuidor->id }}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
								  <div class="modal-dialog modal-lg">
								    <div class="modal-content">

								      <div class="modal-body">

								      <h1>¡Atención!</h1>
								      <h3>Se va a eliminar al Distribuidor: <b>{{ $distribuidor->user->last_name }} {{ $distribuidor->user->first_name }}</b>.</h3>
								      <h3>¿Está seguro?</h3>
								      {{ Form::open(['route'=>['distribuidor.destroy',$distribuidor->id],'id'=>'myForm'.$distribuidor->id,'method'=>'DELETE']) }}
								        <a href="#" onclick="document.getElementById('myForm{{ $distribuidor->id }}').submit();" class="btn btn-danger btn-lg"><b><i class="fas fa-trash fa-2x"></i> Borrar</b></a>
								        <button type="button" class="btn btn-default btn-lg pull-right" data-dismiss="modal"><b><i class="fa fa-thumbs-up fa-2x"></i> Cancelar</b></button>
								      {{ Form::close() }}
								      </div>
								    </div>
								  </div>
								</div>
					  	@endforeach
					  </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

@stop

@section('scripts')
	
	<!-- page script -->
  {{ HTML::script('//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js') }}
  {{ HTML::script('//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js') }}
  {{ HTML::script('//cdn.datatables.net/buttons/1.4.0/js/dataTables.buttons.min.js') }}
  {{ HTML::script('//cdn.datatables.net/buttons/1.4.0/js/buttons.bootstrap.min.js') }}
  {{ HTML::script('//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js') }}
  {{ HTML::script('//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js') }}
  {{ HTML::script('//cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js') }}
  {{ HTML::script('//cdn.datatables.net/buttons/1.4.0/js/buttons.html5.min.js') }}
  {{ HTML::script('//cdn.datatables.net/buttons/1.4.0/js/buttons.print.min.js') }}
  {{ HTML::script('//cdn.datatables.net/buttons/1.4.0/js/buttons.colVis.min.js') }}

  <!-- page script -->
  <script type="text/javascript">
    $(function() {
      $('#distribuidores').dataTable({
        "bPaginate": true,
        "bLengthChange": true,
        "bFilter": true,
        "bSort": true,
        "bInfo": true,
        "sDom": '<"top"Bif>rt<"bottom"pl><"clear">',
        "sButtons": [
          'copy', 'csv', 'excel', 'pdf', 'print'
        ],
        "bAutoWidth": true,
        "oLanguage": {
        "sLengthMenu": "_MENU_ distribuidores por página",
        "sInfo": "Mostrando del _START_ al _END_ de _TOTAL_ distribuidores",
        "sEmptyTable": "No se encontraron datos en la tabla",
        "sInfoEmpty": "Mostrando del 0 al 0 de 0 distribuidores",
        "sInfoFiltered": "(filtrado de un total de _MAX_ distribuidores)",
        "sLoadingRecords": "Cargando...",
        "sProcessing": "Procesando...",
        "sSearch": "Buscar:",
        "sZeroRecords": "No se encontraron registros con la búsqueda",
        "oPaginate": {
          "sNext": "Siguiente",
          "sPrevious": "Anterior",
        }
        },
      });
    });
  </script>

@stop

app/views/sistema/distribuidores/show.blade.php
@extends('dashboard.layouts.dashboard.master')

@section('content')

@include('notifications')

	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Distribuidor: <b><u>{{ $distribuidor->user->first_name }} {{ $distribuidor->user->last_name }}</u></b></h3>
		</div>
		<div class="panel-body">
			<div class="table table-responsive">
				<table class="table clickable">
					<thead>
						<tr>
							<th nowrap>Fecha</th>
							<th nowrap>Folio</th>
							<th nowrap>Compañia</th>
							<th nowrap>Cantidad</th>
							<th nowrap>Comprobante</th>
							<th nowrap>Validado</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($tickets as $ticket)
							<tr>
								<td>{{ $ticket->fecha }}</td>
								<td>{{ $ticket->folio }}</td>
								<td>{{ $ticket->compania }}</td>
								<td class="text-right">$ {{ number_format($ticket->cantidad,2,'.',',') }}</td>
								<td class="text-center">
									<a href="#" id="myImg{{ $ticket->id }}"><i class="fas fa-receipt fa-2x"></i></a>
								</td>
								<td class="text-center">
									@if ($ticket->verificado == 0)
										@if($ticket->compania == 'Conecta')
											<button class="btn btn-success verifyConecta" data-amount="{{$ticket->cantidad}}" data-distribuidor="{{$distribuidor->id}}" data-ticket="{{$ticket->id}}">Verificar</button>
										@elseif($ticket->compania == 'Altcel' || $ticket->compania == null)
											{{ Form::open(['route'=>['ticket.update',$ticket->id,'dist'=>$distribuidor->id],'id'=>'myForm'.$ticket->id,'method'=>'PUT']) }}

												<button type="submit" class="btn btn-success">Verificar</button>

											{{ Form::close() }}
										@endif

										
										
									@else
										<i class="fas fa-check fa-2x" style="color: green;"></i>
									@endif
								</td>
							</tr>

							<!-- The Modal -->
              <div id="myModal{{ $ticket->id }}" class="modal">

                <!-- The Close Button -->
                <span class="close" id="close{{ $ticket->id }}"> <i class="fas fa-times fa-2x"></i> </span>

                <!-- Modal Content (The Image) -->
                <img class="modal-content" id="img01{{ $ticket->id }}" width="70%">

                <!-- Modal Caption (Image Text) -->
                <div id="caption"></div>
              </div>

							<script type="text/javascript">
                // Get the modal
                var modal = document.getElementById('myModal{{ $ticket->id }}');

                // Get the image and insert it inside the modal - use its "alt" text as a caption
                var img = document.getElementById('myImg{{ $ticket->id }}');
                var modalImg = document.getElementById("img01{{ $ticket->id }}");
                img.onclick = function(){
                  modal.style.display = "block";
                  modalImg.src = '{{ asset($ticket->foto_ticket) }}';
                }

                // Get the <span> element that closes the modal
                var span = document.getElementById("close{{ $ticket->id }}");

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                modal.style.display = "none";
                }
              </script>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
<script>
	$('.verifyConecta').click(function(){
		let amount = $(this).data('amount');
		let distribuidor = $(this).data('distribuidor');
		let ticket = $(this).data('ticket');
		
		$.ajax({
			url: "{{URL::route('ticket.update.altcel2')}}",
			data:{dealer:distribuidor,amount:amount,ticket:ticket},
			beforeSend: function(){
				Swal.fire({
					title: 'Actualizando datos...',
					html: 'Espera un poco, un poquito más...',
					showConfirmButton: false,
					didOpen: () => {
						Swal.showLoading();
					}
				});
			},
			success:function(response){
				if(response.http_code == 1){
					Swal.fire({
                        icon: 'success',
                        title: 'Listo',
                        text: 'Ticket verificado.'
                    });
					setTimeout(function(){ location.reload();},1200);
				}else{
					Swal.fire({
                        icon: 'error',
                        title: 'Woops!',
                        text: 'Algo salió mal, consulte a Desarrollo.'
                    });
				}
			}
		});
	});
</script>

@stop