app/routes.php
<?php
//prueba
Route::get('/', function(){
	return View::make('hello');
});

Route::get('soporte', function(){
	return View::make('soporte');
});

Route::get('test', function(){
	return View::make('test');
});

Route::post('prueba', array(
	//'before' => 'csrf',
	'as' =>'prueba',
	'uses'=>'MyController@getIndex'
));

/*===========================================
=            Configuración Admin            =
===========================================*/

Config::set('syntara::views.dashboard-index', 'index');

View::composer('dashboard.layouts.dashboard.master', function ($view) {
	$view->with('siteName', 'Recargas Altcel');
	$view->nest('navPages', 'left-nav');
});


/*=====  End of Configuración Admin  ======*/

/*==================================================
=            Contadores Index Principal            =
==================================================*/

View::composer('index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

View::composer('sistema.altcel2.index', function($view) {
	$view->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first());
});

/*=====  End of Contadores Index Principal  ======*/

/*==================================================
=            Contadores Index Altcel            =
==================================================*/

View::composer('sistema.index', function($view) {
	$view->with('distribuidores', Distribuidor::count())
	     ->with('user', Sentry::getUser())
       ->with('groupDist', Sentry::findGroupByName('Distribuidor'))
       ->with('userDist', Distribuidor::where('user_id',Sentry::getUser()->id)->first())
       ->with('montos',CantRecarga::where('visible',1)->lists('descripcion','id'))
       ->with('totales',TotalRecargaDiaria::all()->take(30));
});

/*=====  End of Contadores Index Altcel  ======*/

/*=================================
=            Catálogos            =
=================================*/

View::composer('sistema.cant_recargas.index', function($view){
	$view->with('cant_recargas', CantRecarga::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'catalogo'), function () {

	Route::resource('cant_recarga', 'CantRecargaController');

});

/*=====  End of Catálogos  ======*/


/*===============================
=            Sistema            =
===============================*/

View::composer('sistema.distribuidores.index', function ($view) {
  $view->with('distribuidores', Distribuidor::all());
});

Route::group(array('before' => 'basicAuth|hasPermissions'), function () {

	Route::resource('distribuidor', 'DistribuidorController');
	Route::resource('recarga', 'RecargaController');
	Route::resource('ticket', 'TicketController');
	Route::resource('conecta', 'ConectaController');
	Route::resource('conecta_cliente', 'ConectaClienteController');
	Route::resource('altcel', 'AltcelController');
	Route::get(
		'ticket-update-altcel2',
		array(
			'as'   => 'ticket.update.altcel2',
			'uses' => 'TicketController@updateAltcel2')
	);
    Route::resource('venta_sim', 'VentaSimController');
    Route::post(
		'venta_sim/actualizar',
		array(
			'as'   => 'venta_sim.actualizar',
			'uses' => 'VentaSimController@actualizar')
	);
});



Route::group(array('before'=>'basicAuth|hasPermissions', 'prefix' => 'recurrente'), function() {
	
	Route::resource('recurrente', 'RecurrenteController');
	Route::resource('empresa', 'EmpresaController');
	Route::resource('telefono', 'TelefonoRecurrenteController');
	Route::resource('correo', 'CorreoRecurrenteController');

});

Route::group(array('before' => 'basicAuth|hasPermissions', 'prefix' => 'altcel2'), function(){
	Route::resource('conecta','Altcel2Controller');

	Route::get(
		'monthly/{msisdn}',
		array(
			'as'   => 'altcel2.monthly',
			'uses' => 'Altcel2Controller@monthly')
	);

	Route::get(
		'save-monthly',
		array(
			'as'   => 'altcel2.save.monthly',
			'uses' => 'Altcel2Controller@saveMonthly')
	);

	Route::get(
		'get-offers-rates-diff/{msisdn}',
		array(
			'as'   => 'altcel2.get.offers.rates.diff',
			'uses' => 'Altcel2Controller@getOffersNRatesDiff')
	);

	Route::get(
		'change.product',
		array(
			'as'   => 'altcel2.change.product',
			'uses' => 'Altcel2Controller@changeProduct')
	);

	Route::get(
		'surplus/{msisdn}',
		array(
			'as'   => 'altcel2.surplus',
			'uses' => 'Altcel2Controller@surplus')
	);

	Route::get(
		'purchase-product',
		array(
			'as'   => 'altcel2.purchase',
			'uses' => 'Altcel2Controller@purchaseProduct')
	);

	Route::get(
		'verify-exists-msisdn',
		array(
			'as'   => 'altcel2.verify.exists.msisdn',
			'uses' => 'Altcel2Controller@verifyExistsMSISDN')
	);

	Route::get(
		'unbarring',
		array(
			'as'   => 'altcel2.unbarring',
			'uses' => 'Altcel2Controller@unbarring')
	);
});

/*=====  End of Sistema  ======*/

/*==================================
=  Recuperación de contraseña      =
==================================*/

Route::get(
	'recover_password/{id}/{resetCode}',
	array(
		'as'   => 'recover.newPassword',
		'uses' => 'RecoverController@newPassword')
);


Route::post(
	'recover_password/{id}/{resetCode}',
	array(
	'as'   => 'recover.newPasswordPost',
	'uses' => 'RecoverController@newPasswordPost')
);

Route::resource('recover', 'RecoverController');

/*=====  End of Recuperación de contraseña  ======*/

app/views/index.blade.php
@extends(Config::get('syntara::views.master'))

{{ HTML::style('css/form.css') }}



@section('content')

@include('notifications')

@if (Session::has('popup'))


  <script>
    var myWindow = window.open("{{ URL::to('recarga', Session::get('popup')) }}", "", "width=800,height=800");
  </script>
@endif

  @if (Sentry::check())

    <div class="panel panel-danger">
      <div class="panel-body">
  
          <div class="row">

            @if ($currentUser->hasAccess('view-distribuidor-list'))

              <div class="col-lg-4 col-xs-12">
                <!-- small box -->
                <div class="small-box bg-aqua">
                  <div class="inner">
                    <h3>
                      {{ $distribuidores }}
                    </h3>
                    <p>
                      Distribuidores
                    </p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-cash-register"></i>
                  </div>
                  <a href="{{ URL::route('distribuidor.index') }}" class="small-box-footer">
                    Ver <i class="fa fa-arrow-circle-right"></i>
                  </a>
                </div>
              </div><!-- ./col -->

            @endif
              
          </div>

      </div>
    </div>

    @if ($user->inGroup($groupDist))
      <div class="row">
        <div class="col-md-4">
          <a href="{{ URL::route('altcel.index') }}">
            <div class="panel panel-danger">
              <div class="panel-body text-center">
                <img src="{{ asset('images/Recarga_Altcel.png') }}" width="150px" alt="">
              </div>
            </div>
          </a>

        </div>
        <div class="col-md-4">
          <a href="{{ URL::route('altcel2.conecta.index')}}">
            <div class="panel panel-danger">
              <div class="panel-body text-center">
                <img src="{{ asset('images/Recarga_conecta.png') }}" width="150px" alt="">
              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
            <a href="{{ URL::route('venta_sim.index')}}">
              <div class="panel panel-danger">
                <div class="panel-body text-center">
                    <img src="{{ asset('images/Ventas_Sim.png') }}" width="150px" alt="">
                </div>
              </div>
            </a>
          </div>
        <!-- {{ Sentry::getUser()->username }} -->
      </div>
    @else
      <div class="col-md-12">
        <!-- LINE CHART -->
        <div class="box box-info">
          <div class="box-header">
            <h3 class="box-title">Recargas Diarias</h3>
          </div>
          <div class="box-body chart-responsive">
            <div class="chart" id="line-chart" style="height: 300px;"></div>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col (RIGHT) -->
    @endif

  @endif
@stop

@section('scripts')

  <script>
    function DisableButton(b)
    {
      /*b.disabled = true;
      b.value = 'Haciendo Recarga...';
      b.form.submit();*/

    }
  </script>

  <script type="text/javascript">

    $("#form").validate({
      rules: {
        telefono: {
          digits: true,
          minlength: 10,
          maxlength:10
        },
        tel_conf:{
          equalTo:"#telefono"
        },
      },
      success: function(label) {
        label.addClass("valid").text("Ok!")
      },
      submitHandler: function() {
        //alert("Submitted!")
        $('#SubmitButton').prop('disabled', 'disabled');
        form.submit();
      }
    });

    $(function() {
        startTime();
        $(".center").center();
        $(window).resize(function() {
            $(".center").center();
        });
    });

    /*  */
    function startTime()
    {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();

        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);

        //Check for PM and AM
        var day_or_night = (h > 11) ? "PM" : "AM";

        //Convert to 12 hours system
        if (h > 12)
            h -= 12;

        //Add time to the headline and update every 500 milliseconds
        $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
        setTimeout(function() {
            startTime()
        }, 500);
    }

    function checkTime(i)
    {
        if (i < 10)
        {
            i = "0" + i;
        }
        return i;
    }

    // LINE CHART
    var line = new Morris.Area({
      parseTime:false,
      element: 'line-chart',
      resize: true,
      data: [
        @foreach ($totales as $total)
          {y: '{{ $total->fecha }}', item1: {{ $total->total }}},
        @endforeach
      ],
      xkey: 'y',
      ykeys: ['item1'],
      labels: ['Recargas'],
      lineColors: ['#0CAAE0'],
      hideHover: 'auto',
      behaveLikeLine: true,
      pointFillColors:['#ffffff'],
      pointStrokeColors: ['black'],
    });

  </script>
  {{ HTML::script('js/form.js') }}
@endsection

app/views/index_1.blade.php
@extends(Config::get('syntara::views.master'))

app/views/left-nav.blade.php
@if (Sentry::check())

	@if ($currentUser->hasAccess('catalogs-management'))
		<li class="treeview">
			<a href="#">
				<i class="fas fa-cogs"></i> <span>Configuración</span>
				<i class="fas fa-angle-left pull-right"></i>
			</a>
			<ul class="treeview-menu">
				<li class="treeview" id="Menu1">
					<a href="#">
						<i class="fas fa-book"></i> <span>Catálogos</span>
						<i class="fas fa-angle-left pull-right"></i>
					</a>
					<ul class="treeview-menu" id="Menu1-1">
						@if ($currentUser->hasAccess('view-cant_recarga-list'))
							<li><a href="{{ URL::route('catalogo.cant_recarga.index') }}"><i class="fas fa-file-invoice-dollar"></i> Cant. de Recarga</a></li>
						@endif
					</ul>
				</li>
			</ul>
		</li>
	@endif

	@if ($currentUser->hasAccess('view-distribuidor-list'))

		<li><a href="{{ URL::route('distribuidor.index') }}"><i class="fas fa-cash-register"></i> Distribuidores</a></li>

	@endif

	@if ($currentUser->hasAccess('view-recarga-list'))
		
		<li><a href="{{ URL::route('recarga.index') }}"><i class="fas fa-mobile"></i> Recargas</a></li>

	@endif

	@if ($currentUser->hasAccess('view-ticket-list'))

		<li><a href="{{ URL::route('ticket.index') }}"><i class="fas fa-file-invoice-dollar"></i> Compra de Saldo</a></li>

	@endif

@endif

app/views/notifications.blade.php
@if (Session::has('errors'))
    <!--
    <div class="callout callout-danger">
    <h4>Errores:</h4>
    @foreach ($errors->all() as $message)
        <i class="fas fa-times"></i> {{ $message }} <br>
    @endforeach
    </div>
    -->
    <!-- Modal -->
    <div class="modal fade" id="myModalErrors" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body text-center">
            <h1 class="modal-title" id="myModalLabel"><b><i class="fas fa-thumbs-down fa-5x"></i></b></h1>
            <br><br>
            @foreach ($errors->all() as $message)
                <h4><i class="fas fa-times"></i> {{ $message }}</h4> <br>
            @endforeach
          </div>
        </div>
      </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#myModalErrors').modal('show');
            $('#myModalErrors').on('shown', function() {
                $("#txtname").focus();
            })
        });
    </script>
@endif


@if (Session::has('success'))
	<!--<div class="alert alert-success alert-dismissable">
    <i class="fas fa-check"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <b><i class="fas fa-thumbs-up"></i></b> {{ Session::get('success') }}
	</div>-->

    <!-- Modal -->
    <div class="modal fade" id="myModalSuccess" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body success-modal-body text-center">
            <h1 class="modal-title" id="myModalLabel"><b><i class="fas fa-thumbs-up fa-5x"></i></b><br> {{ Session::get('success') }}</h1>
          </div>
        </div>
      </div>
    </div>
    <script>
        $(document).ready(function() {
            $('#myModalSuccess').modal('show');
            $('#myModalSuccess').on('shown', function() {
                $("#txtname").focus();
            });
            setTimeout(
              function() {
                $('#myModalSuccess').modal('hide');
              }, 3000);
            });
    </script>
@endif

@if (Session::has('error'))
<!--
	<div class="alert alert-danger alert-dismissable">
    <i class="fas fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <b><i class="fas fa-times"></i></b> {{ Session::get('error') }}
	</div>
-->
  <!-- Modal -->
  <div class="modal fade" id="myModalError" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body info-modal-body text-center">
          <h1 class="modal-title" id="myModalLabel"><b><i class="fas fa-exclamation-triangle fa-5x"></i></b><br> {{ Session::get('error') }}</h1>
        </div>
      </div>
    </div>
  </div>
  <script>
  $(document).ready(function() {
    $('#myModalError').modal('show');
    $('#myModalError').on('shown', function() {
        $("#txtname").focus();
    });
    setTimeout(
      function() {
        $('#myModalError').modal('hide');
    }, 3000);
  });
  </script>
@endif

@if (Session::has('info'))
  <!--
    <div class="alert alert-info alert-dismissable">
      <i class="fas fa-check"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <b><i class="fas fa-info-sign"></i></b> {{ Session::get('info') }}
    </div>
  -->
    <!-- Modal -->
    <div class="modal fade" id="myModalInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body info-modal-body text-center">
            <h1 class="modal-title" id="myModalLabel"><b><i class="fas fa-info-circle fa-5x"></i></b><br> {{ Session::get('info') }}</h1>
          </div>
        </div>
      </div>
    </div>
    <script>
    $(document).ready(function() {
      $('#myModalInfo').modal('show');
      $('#myModalInfo').on('shown', function() {
          $("#txtname").focus();
      });
    });
    </script>
@endif

app/views/ntf.blade.php
@if (Session::has('errors'))
    <div class="callout callout-danger">
    <h4>Errores:</h4>
    @foreach ($errors->all() as $message)
        <i class="fas fa-times"></i> {{ $message }} <br>
    @endforeach
    </div>
@endif


@if (Session::has('success'))
	<div class="alert alert-success alert-dismissable">
    <i class="fas fa-check"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <b><i class="fas fa-thumbs-up"></i></b> {{ Session::get('success') }}
	</div>
@endif

@if (Session::has('error'))
	<div class="alert alert-danger alert-dismissable">
    <i class="fas fa-ban"></i>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <b><i class="fas fa-times"></i></b> {{ Session::get('error') }}
	</div>
@endif

@if (Session::has('info'))
    <div class="alert alert-info alert-dismissable">
      <i class="fas fa-check"></i>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <b><i class="fas fa-info-sign"></i></b> {{ Session::get('info') }}
    </div>
@endif

app/views/soporte.blade.php
@extends('layouts.master')

@section('content')
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
	    <div class="panel panel-default">
	        <div class="panel-heading" role="tab" id="heading1">
	            <h4 class="panel-title">
	                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
	                    iPhone
	                </a>
	            </h4>
	        </div>
	        <div id="collapse1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading1">
	            <div class="panel-body">
	                <p>
	                	<div>
									    	<b>DESCARGAR <b>Recargas AltCl</b></b> <br>

									    		Descargar <b>Recargas AltCl</b> para dispositivos <a href="itms-apps://apps.apple.com/mx/app/recargas-altcl/id1520253503">iPhone <i class="fas fa-external-link-alt"></i></a>. <br><br>
									    		<b><b>Recargas AltCl</b> está disponible para:</b> <br>
													<ul>
														<li>iPhone</li>
														<li>iOS 12.4 o versiones posteriores</li>
														<li>Idioma Español únicamente</li>
													</ul>
													<br>
									    		<b>Instalar <b>Recargas AltCl</b></b> <br>
									    		<ol>
									    			<li>En tu dispositivo iPhone o iPad, accede a <b>Recargas AltCl</b> en App Store.</li>
									    			<li>Toca Obtener.</li>
									    			<li>Toca Instalar.</li>
									    			<li>Introduce la contraseña de tu ID de Apple y toca OK.</li>
									    			<li>Para empezar a navegar, ve a la pantalla de inicio. Toca la aplicación <b>Recargas AltCl</b> <img src="{{ asset('images/icono.png') }}" alt="<b>Recargas AltCl</b>" width="18px"></li>
									    		</ol>
													 <br>
													Prueba a desinstalar <b>Recargas AltCl</b> e instalarlo de nuevo para solucionar problemas con tu motor de búsqueda, Flash, ventanas emergentes o actualizaciones del navegador. <br>
													<br>
													<b>Añadir <b>Recargas AltCl</b> al Dock de un iPhone</b> <br>
													Después de instalar <b>Recargas AltCl</b> en un iPhone o iPad, añádelo al Dock para buscarlo y abrirlo fácilmente: <br>	
													<ol>
														<li>Mantén pulsada una aplicación del Dock para liberar espacio.</li>
														<li>Arrástrala y suéltala en la pantalla principal.</li>
														<li>Mantén pulsada la aplicación <b>Recargas AltCl</b> <img src="{{ asset('images/icono.png') }}" alt="<b>Recargas AltCl</b>" width="18px"></li>
														<li>Arrástrala y suéltala en tu Dock.</li>
														<li>Pulsa el botón de inicio.</li>
													</ol>				
													
									    </div>
	                </p>
	            </div>
	        </div>
	    </div>
	    <div class="panel panel-default">
	        <div class="panel-heading" role="tab" id="heading2">
	            <h4 class="panel-title">
	                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
	                    Android
	                </a>
	            </h4>
	        </div>
	        <div id="collapse2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading2">
	            <div class="panel-body">
	                <p>
	                	<div>
								    	Descargar <b>Recargas AltCl</b>
											Descarga <b>Recargas AltCl</b> para <a href="https://play.google.com/store/apps/details?id=com.altcel.posaltcel" target="_blank">teléfonos y tablets Android <i class="fas fa-external-link-alt"></i></a>. <br>

											<b>Recargas AltCl</b> está disponible para teléfonos y tablets con Android 7 (Nougat) o versiones posteriores. <br><br>

											<b>Instalar <b>Recargas AltCl</b></b> <br>
											<ol>
												<li>En tu teléfono o tablet Android, accede a <b>Recargas AltCl</b> en <a href="#" target="_blank">Google Play.</a></li>
												<li>Toca Instalar.</li>
												<li>Toca Aceptar.</li>
												<li>Para empezar a navegar, ve a la pantalla de inicio o al menú de aplicaciones. Toca la aplicación <b>Recargas AltCl</b> <img src="{{ asset('images/icono.png') }}" alt="Recargas AltCl" width="18px"></li>
											</ol>

											<br>
											Prueba a desinstalar <b>Recargas AltCl</b> e instalarlo de nuevo para solucionar problemas con tu buscador, Flash, ventanas emergentes o actualizaciones del navegador.
								    </div>
	                </p>
	            </div>
	        </div>
	    </div>
	</div>
@endsection

@section('scripts')
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
@endsection

@section('head')
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	
	<!------ Include the above in your HEAD tag ---------->
@endsection

app/views/test.blade.php
@extends(Config::get('syntara::views.master'))

{{ HTML::style('css/form.css') }}



@section('content')

@include('notifications')

@stop